### ISSUE TITLE
bot currently fails 

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/planemo-monitor#45]
```
dockerhub-toolshed/multi-package-containers already existsTraceback (most recent call last):
  File "/home/runner/work/planemo-monitor/planemo-monitor/.venv/bin/planemo", line 8, in <module>
    sys.exit(planemo())
  File "/home/runner/work/planemo-monitor/planemo-monitor/.venv/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/runner/work/planemo-monitor/planemo-monitor/.venv/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/runner/work/planemo-monitor/planemo-monitor/.venv/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/runner/work/planemo-monitor/planemo-monitor/.venv/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/runner/work/planemo-monitor/planemo-monitor/.venv/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/runner/work/planemo-monitor/planemo-monitor/.venv/lib/python3.8/site-packages/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/runner/work/planemo-monitor/planemo-monitor/.venv/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/runner/work/planemo-monitor/planemo-monitor/.venv/lib/python3.8/site-packages/planemo/cli.py", line 102, in handle_blended_options
    return f(*args, **kwds)
  File "/home/runner/work/planemo-monitor/planemo-monitor/.venv/lib/python3.8/site-packages/planemo/commands/cmd_container_register.py", line 146, in cli
    registry_target.write_targets(ctx, target_filename, mulled_targets, tag, base_image)
  File "/home/runner/work/planemo-monitor/planemo-monitor/.venv/lib/python3.8/site-packages/planemo/commands/cmd_container_register.py", line 211, in write_targets
    targets = to_target_str(mulled_targets)
  File "/home/runner/work/planemo-monitor/planemo-monitor/.venv/lib/python3.8/site-packages/planemo/commands/cmd_container_register.py", line 220, in to_target_str
    target_str = f"{target.package_name}={target.version}"
AttributeError: 'CondaTarget' object has no attribute 'package_name'
fatal: repository '# needs to stay alone, its big enough' does not exist

**Comment by bernt-matthias** [comment]
Workaround: https://github.com/galaxyproject/planemo-monitor/pull/46
